import { ParametroUrbanisticoDistrital } from "@/types/configuracion";

/**
 * Catálogo de 22 normas y parámetros urbanísticos de Lima Metropolitana y Callao.
 * Basado en Ordenanzas Distritales vigentes, Reajustes Integrales de Zonificación (RIZ)
 * y disposiciones metropolitanas (Ord. 2361-MML, Ord. 1076-MML, Ley 29090).
 */
export const parametrosUrbanisticosNormativos: ParametroUrbanisticoDistrital[] = [
  // 1. MIRAFLORES - RDA (Av. Pardo / Benavides / Arequipa)
  {
    id: "NORM-MIRA-001",
    distrito: "Miraflores",
    zonificacion: "RDA",
    alturaMaxPisos: 15,
    alturaMaxMetros: 45.0,
    coeficienteEdificacion: 4.5,
    areaLibreMinPct: 35.0,
    frenteMinimoM: 15.0,
    loteMinimoM2: 600.0,
    estacionamientosRequeridos: "1 por cada 1.5 departamentos + 10% visitas",
    ordenanzaReferencia: "Ord. 618-MM / Ord. 648-MM",
    fechaAprobacion: "2024-03-15",
    vigencia: true,
    incentivoViviendaSostenible: {
      activo: true,
      alturaAdicionalPisos: 2,
      areaLibreReducidaPct: 30.0,
      normaRef: "Ord. 510/MM Bono Verde",
    },
    notasNormativas:
      "Aplica en predios con frente a avenidas mayores a 20m de ancho. Retiro municipal frontal de 5.00m.",
    updatedAt: "2026-06-10T14:30:00Z",
    updatedBy: "Alvaro Barrenechea",
  },
  // 2. MIRAFLORES - RDM (Residencial de Densidad Media)
  {
    id: "NORM-MIRA-002",
    distrito: "Miraflores",
    zonificacion: "RDM",
    alturaMaxPisos: 7,
    alturaMaxMetros: 21.0,
    coeficienteEdificacion: 3.2,
    areaLibreMinPct: 35.0,
    frenteMinimoM: 12.0,
    loteMinimoM2: 450.0,
    estacionamientosRequeridos: "1 por departamento",
    ordenanzaReferencia: "Ord. 618-MM",
    fechaAprobacion: "2024-03-15",
    vigencia: true,
    notasNormativas:
      "Frente a calles secundarias. Prohibida la edificación comercial en primer nivel salvo consultorio médico anexo.",
    updatedAt: "2026-05-12T11:00:00Z",
    updatedBy: "Sofia Mendoza",
  },
  // 3. MIRAFLORES - CZ (Comercio Zonal - Ovalo Gutiérrez / Larco)
  {
    id: "NORM-MIRA-003",
    distrito: "Miraflores",
    zonificacion: "CZ",
    alturaMaxPisos: 17,
    alturaMaxMetros: 51.0,
    coeficienteEdificacion: 5.8,
    areaLibreMinPct: 20.0,
    frenteMinimoM: 15.0,
    loteMinimoM2: 800.0,
    estacionamientosRequeridos: "1 cada 50m² comerciales + 1 por depto",
    ordenanzaReferencia: "Ord. 618-MM",
    fechaAprobacion: "2024-03-15",
    vigencia: true,
    notasNormativas:
      "Usos compatibles: Hotelería 4/5*, oficinas corporativas clase A+, retail comercial y vivienda mixta.",
    updatedAt: "2026-07-02T16:20:00Z",
    updatedBy: "Diego Palacios",
  },

  // 4. SAN ISIDRO - RDA (Pezet / Coronel Portillo)
  {
    id: "NORM-SI-001",
    distrito: "San Isidro",
    zonificacion: "RDA",
    alturaMaxPisos: 12,
    alturaMaxMetros: 36.0,
    coeficienteEdificacion: 4.2,
    areaLibreMinPct: 40.0,
    frenteMinimoM: 18.0,
    loteMinimoM2: 800.0,
    estacionamientosRequeridos: "2 por departamento + 15% visitas",
    ordenanzaReferencia: "Ord. 572-MSI / Ord. 1076-MML",
    fechaAprobacion: "2023-11-20",
    vigencia: true,
    notasNormativas:
      "Área libre obligatoria al 40%. Restricción estricta de altura frente al Lima Golf Club.",
    updatedAt: "2026-06-15T09:15:00Z",
    updatedBy: "Alvaro Barrenechea",
  },
  // 5. SAN ISIDRO - CM / CZ (Centro Financiero - Canaval y Moreyra / Begonias)
  {
    id: "NORM-SI-002",
    distrito: "San Isidro",
    zonificacion: "CM",
    alturaMaxPisos: 25,
    alturaMaxMetros: 85.0,
    coeficienteEdificacion: 7.5,
    areaLibreMinPct: 15.0,
    frenteMinimoM: 20.0,
    loteMinimoM2: 1200.0,
    estacionamientosRequeridos: "1 cada 35m² útiles de oficina",
    ordenanzaReferencia: "Ord. 1076-MML / Ord. 593-MSI",
    fechaAprobacion: "2023-08-10",
    vigencia: true,
    incentivoViviendaSostenible: {
      activo: true,
      alturaAdicionalPisos: 5,
      areaLibreReducidaPct: 15.0,
      normaRef: "Reglamento de Acumulación Predial Torre Corporativa",
    },
    notasNormativas:
      "En predios con área > 2,000 m² se autoriza altura libre hasta 30 pisos con estudio de impacto vial aprobado.",
    updatedAt: "2026-07-18T10:45:00Z",
    updatedBy: "Alvaro Barrenechea",
  },
  // 6. SAN ISIDRO - RDM (Sectores 3 y 4 - Cavenecia / Dasso)
  {
    id: "NORM-SI-003",
    distrito: "San Isidro",
    zonificacion: "RDM",
    alturaMaxPisos: 6,
    alturaMaxMetros: 18.0,
    coeficienteEdificacion: 3.0,
    areaLibreMinPct: 45.0,
    frenteMinimoM: 15.0,
    loteMinimoM2: 500.0,
    estacionamientosRequeridos: "2 por depto",
    ordenanzaReferencia: "Ord. 572-MSI",
    fechaAprobacion: "2023-11-20",
    vigencia: true,
    notasNormativas:
      "Máximo 1 departamento por piso en lotes de frente inferior a 15m. Prohibido subdivisión.",
    updatedAt: "2026-04-20T17:00:00Z",
    updatedBy: "Sofia Mendoza",
  },

  // 7. SANTIAGO DE SURCO - RDA (Chacarilla / El Polo)
  {
    id: "NORM-SURCO-001",
    distrito: "Santiago de Surco",
    zonificacion: "RDA",
    alturaMaxPisos: 10,
    alturaMaxMetros: 30.0,
    coeficienteEdificacion: 3.8,
    areaLibreMinPct: 35.0,
    frenteMinimoM: 14.0,
    loteMinimoM2: 600.0,
    estacionamientosRequeridos: "1.5 por depto",
    ordenanzaReferencia: "Ord. 676-MSS / Ord. 595-MSS",
    fechaAprobacion: "2024-01-18",
    vigencia: true,
    notasNormativas:
      "Frente a avenidas principales (Primavera, Benavides, Caminos del Inca). Retiro frontal de 3.00m.",
    updatedAt: "2026-05-30T12:00:00Z",
    updatedBy: "Diego Palacios",
  },
  // 8. SANTIAGO DE SURCO - CZ (Caminos del Inca / Higuereta)
  {
    id: "NORM-SURCO-002",
    distrito: "Santiago de Surco",
    zonificacion: "CZ",
    alturaMaxPisos: 12,
    alturaMaxMetros: 36.0,
    coeficienteEdificacion: 5.0,
    areaLibreMinPct: 25.0,
    frenteMinimoM: 15.0,
    loteMinimoM2: 750.0,
    estacionamientosRequeridos: "1 cada 40m² comerciales",
    ordenanzaReferencia: "Ord. 676-MSS",
    fechaAprobacion: "2024-01-18",
    vigencia: true,
    notasNormativas:
      "Admite uso mixto comercial-residencial con comercio en niveles 1 y 2.",
    updatedAt: "2026-06-05T15:10:00Z",
    updatedBy: "Diego Palacios",
  },

  // 9. SAN BORJA - RDA (Av. Javier Prado / Aviación / San Borja Norte)
  {
    id: "NORM-SB-001",
    distrito: "San Borja",
    zonificacion: "RDA",
    alturaMaxPisos: 10,
    alturaMaxMetros: 30.0,
    coeficienteEdificacion: 3.6,
    areaLibreMinPct: 35.0,
    frenteMinimoM: 12.0,
    loteMinimoM2: 500.0,
    estacionamientosRequeridos: "1.5 por departamento",
    ordenanzaReferencia: "Ord. 621-MSB / Ord. 681-MSB",
    fechaAprobacion: "2023-12-05",
    vigencia: true,
    notasNormativas:
      "Restricción explícita de vivienda VIS. Altura condicionada a frentes de avenida no menor a 25m.",
    updatedAt: "2026-06-25T11:20:00Z",
    updatedBy: "Alvaro Barrenechea",
  },
  // 10. SAN BORJA - RDM (Interior residencial canónico)
  {
    id: "NORM-SB-002",
    distrito: "San Borja",
    zonificacion: "RDM",
    alturaMaxPisos: 4,
    alturaMaxMetros: 12.0,
    coeficienteEdificacion: 2.8,
    areaLibreMinPct: 40.0,
    frenteMinimoM: 10.0,
    loteMinimoM2: 300.0,
    estacionamientosRequeridos: "1 por departamento",
    ordenanzaReferencia: "Ord. 621-MSB",
    fechaAprobacion: "2023-12-05",
    vigencia: true,
    notasNormativas:
      "Protección estricta de perfil residencial. No se permite azotea habitable comercial.",
    updatedAt: "2026-05-18T14:40:00Z",
    updatedBy: "Sofia Mendoza",
  },

  // 11. JESÚS MARÍA - RDA (Av. Brasil / Av. Salaverry)
  {
    id: "NORM-JM-001",
    distrito: "Jesús María",
    zonificacion: "RDA",
    alturaMaxPisos: 20,
    alturaMaxMetros: 60.0,
    coeficienteEdificacion: 5.5,
    areaLibreMinPct: 30.0,
    frenteMinimoM: 12.0,
    loteMinimoM2: 600.0,
    estacionamientosRequeridos: "1 por cada 2 deptos (hasta 65m²)",
    ordenanzaReferencia: "Ord. 657-MDJM / Ord. 670-MDJM",
    fechaAprobacion: "2024-02-12",
    vigencia: true,
    incentivoViviendaSostenible: {
      activo: true,
      alturaAdicionalPisos: 2,
      areaLibreReducidaPct: 25.0,
      normaRef: "Certificación EDGE / Bono Verde Mivivienda",
    },
    notasNormativas:
      "Alta rotación para proyectos de 1 y 2 dormitorios. Frente a Av. Brasil permite hasta 20 pisos con retiro.",
    updatedAt: "2026-07-10T09:00:00Z",
    updatedBy: "Sofia Mendoza",
  },
  // 12. JESÚS MARÍA - CZ (Av. San Felipe / Garzón)
  {
    id: "NORM-JM-002",
    distrito: "Jesús María",
    zonificacion: "CZ",
    alturaMaxPisos: 15,
    alturaMaxMetros: 45.0,
    coeficienteEdificacion: 5.0,
    areaLibreMinPct: 25.0,
    frenteMinimoM: 12.0,
    loteMinimoM2: 500.0,
    estacionamientosRequeridos: "1 cada 40m²",
    ordenanzaReferencia: "Ord. 657-MDJM",
    fechaAprobacion: "2024-02-12",
    vigencia: true,
    notasNormativas:
      "Apto para strip centers, laboratorios médicos, oficinas híbridas y vivienda multifamiliar.",
    updatedAt: "2026-06-12T13:30:00Z",
    updatedBy: "Sofia Mendoza",
  },

  // 13. LINCE - RDA (Av. Arenales / Av. Arequipa)
  {
    id: "NORM-LINCE-001",
    distrito: "Lince",
    zonificacion: "RDA",
    alturaMaxPisos: 20,
    alturaMaxMetros: 60.0,
    coeficienteEdificacion: 5.8,
    areaLibreMinPct: 25.0,
    frenteMinimoM: 10.0,
    loteMinimoM2: 450.0,
    estacionamientosRequeridos: "1 por cada 2 deptos",
    ordenanzaReferencia: "Ord. 485-MDL / Ord. 498-MDL",
    fechaAprobacion: "2023-09-28",
    vigencia: true,
    incentivoViviendaSostenible: {
      activo: true,
      alturaAdicionalPisos: 2,
      areaLibreReducidaPct: 20.0,
      normaRef: "Ordenanza Promotora de Densificación Sostenible Lince",
    },
    notasNormativas:
      "Eje de alta demanda para inversionistas de renta corta y coliving juvenil.",
    updatedAt: "2026-07-08T15:00:00Z",
    updatedBy: "Alvaro Barrenechea",
  },

  // 14. BARRANCO - RDA (Av. Grau / Av. Pedro de Osma)
  {
    id: "NORM-BARR-001",
    distrito: "Barranco",
    zonificacion: "RDA",
    alturaMaxPisos: 7,
    alturaMaxMetros: 21.0,
    coeficienteEdificacion: 3.2,
    areaLibreMinPct: 30.0,
    frenteMinimoM: 10.0,
    loteMinimoM2: 400.0,
    estacionamientosRequeridos: "1 por depto",
    ordenanzaReferencia: "Ord. 590-MDB",
    fechaAprobacion: "2023-06-14",
    vigencia: true,
    notasNormativas:
      "Sujeto a dictamen de ProLima y Ministerio de Cultura por zona de amortiguamiento monumental.",
    updatedAt: "2026-05-22T10:15:00Z",
    updatedBy: "Diego Palacios",
  },

  // 15. MAGDALENA DEL MAR - RDA (Av. Brasil / Javier Prado Oeste)
  {
    id: "NORM-MAGD-001",
    distrito: "Magdalena del Mar",
    zonificacion: "RDA",
    alturaMaxPisos: 16,
    alturaMaxMetros: 48.0,
    coeficienteEdificacion: 4.8,
    areaLibreMinPct: 30.0,
    frenteMinimoM: 12.0,
    loteMinimoM2: 550.0,
    estacionamientosRequeridos: "1 por depto",
    ordenanzaReferencia: "Ord. 142-MDMM / Ord. 2361-MML",
    fechaAprobacion: "2024-04-10",
    vigencia: true,
    notasNormativas:
      "Frente al malecón Castagnola y Av. Brasil se aplican retiros escalonados a partir del piso 10.",
    updatedAt: "2026-06-01T16:00:00Z",
    updatedBy: "Sofia Mendoza",
  },

  // 16. SAN MIGUEL - RDA (Av. Costanera / La Marina)
  {
    id: "NORM-SM-001",
    distrito: "San Miguel",
    zonificacion: "RDA",
    alturaMaxPisos: 15,
    alturaMaxMetros: 45.0,
    coeficienteEdificacion: 4.2,
    areaLibreMinPct: 30.0,
    frenteMinimoM: 12.0,
    loteMinimoM2: 500.0,
    estacionamientosRequeridos: "1 por depto",
    ordenanzaReferencia: "Ord. 450-MDSM",
    fechaAprobacion: "2023-10-15",
    vigencia: true,
    notasNormativas:
      "Sector Costanera con vista al Océano Pacífico, excelente tracción para proyectos de primera vivienda.",
    updatedAt: "2026-05-15T11:45:00Z",
    updatedBy: "Diego Palacios",
  },

  // 17. CALLAO - I1 (Industrial Logístico - Av. Elmer Faucett / Av. Argentina)
  {
    id: "NORM-CALLAO-001",
    distrito: "Callao",
    zonificacion: "I1",
    alturaMaxPisos: 4,
    alturaMaxMetros: 18.0,
    coeficienteEdificacion: 2.5,
    areaLibreMinPct: 20.0,
    frenteMinimoM: 20.0,
    loteMinimoM2: 1500.0,
    estacionamientosRequeridos: "1 cada 100m² + patio de maniobras",
    ordenanzaReferencia: "Ord. Prov. 015-2018-MPC",
    fechaAprobacion: "2023-05-10",
    vigencia: true,
    notasNormativas:
      "Eje estratégico logístico-aeroportuario adyacente a la ampliación del Aeropuerto Internacional Jorge Chávez.",
    updatedAt: "2026-07-20T17:30:00Z",
    updatedBy: "Alvaro Barrenechea",
  },

  // 18. CALLAO - RDA (Costanera Callao / Bellavista)
  {
    id: "NORM-CALLAO-002",
    distrito: "Callao",
    zonificacion: "RDA",
    alturaMaxPisos: 12,
    alturaMaxMetros: 36.0,
    coeficienteEdificacion: 3.8,
    areaLibreMinPct: 30.0,
    frenteMinimoM: 12.0,
    loteMinimoM2: 600.0,
    estacionamientosRequeridos: "1 por depto",
    ordenanzaReferencia: "Ord. Prov. 015-2018-MPC",
    fechaAprobacion: "2023-05-10",
    vigencia: true,
    notasNormativas:
      "Proyectos residenciales con vista frontal a la bahía del Callao y La Punta.",
    updatedAt: "2026-06-18T10:00:00Z",
    updatedBy: "Diego Palacios",
  },

  // 19. ATE - I1 / I2 (Separadora Industrial / Nicolás Ayllón)
  {
    id: "NORM-ATE-001",
    distrito: "Ate",
    zonificacion: "I1",
    alturaMaxPisos: 4,
    alturaMaxMetros: 16.0,
    coeficienteEdificacion: 2.2,
    areaLibreMinPct: 25.0,
    frenteMinimoM: 20.0,
    loteMinimoM2: 2000.0,
    estacionamientosRequeridos: "1 cada 80m² + 2 muelles de carga",
    ordenanzaReferencia: "Ord. 1099-MML / Ord. 2361-MML",
    fechaAprobacion: "2023-04-18",
    vigencia: true,
    notasNormativas:
      "Destinado a industria ligera inofensiva, bodegas de última milla, datacenters y ensamblaje.",
    updatedAt: "2026-07-15T14:10:00Z",
    updatedBy: "Alvaro Barrenechea",
  },

  // 20. ATE - CZ (Prolongación Javier Prado / Ceres)
  {
    id: "NORM-ATE-002",
    distrito: "Ate",
    zonificacion: "CZ",
    alturaMaxPisos: 12,
    alturaMaxMetros: 36.0,
    coeficienteEdificacion: 4.5,
    areaLibreMinPct: 25.0,
    frenteMinimoM: 14.0,
    loteMinimoM2: 800.0,
    estacionamientosRequeridos: "1 cada 40m² comerciales",
    ordenanzaReferencia: "Ord. 2361-MML",
    fechaAprobacion: "2023-04-18",
    vigencia: true,
    notasNormativas:
      "Eje de alta conectividad con Línea 2 del Metro de Lima.",
    updatedAt: "2026-06-30T11:00:00Z",
    updatedBy: "Sofia Mendoza",
  },

  // 21. LA MOLINA - RDB (Residencial de Densidad Baja - Rinconada / La Planicie)
  {
    id: "NORM-MOL-001",
    distrito: "La Molina",
    zonificacion: "RDB",
    alturaMaxPisos: 3,
    alturaMaxMetros: 9.0,
    coeficienteEdificacion: 1.6,
    areaLibreMinPct: 50.0,
    frenteMinimoM: 18.0,
    loteMinimoM2: 1000.0,
    estacionamientosRequeridos: "3 por vivienda",
    ordenanzaReferencia: "Ord. 410-MDLM",
    fechaAprobacion: "2023-07-22",
    vigencia: true,
    notasNormativas:
      "Vivienda unifamiliar exclusiva. Altísima área libre al 50%. Prohibido edificio de departamentos.",
    updatedAt: "2026-05-10T15:20:00Z",
    updatedBy: "Alvaro Barrenechea",
  },

  // 22. LA MOLINA - CZ (Av. Javier Prado Este / Raúl Ferrero)
  {
    id: "NORM-MOL-002",
    distrito: "La Molina",
    zonificacion: "CZ",
    alturaMaxPisos: 6,
    alturaMaxMetros: 18.0,
    coeficienteEdificacion: 3.5,
    areaLibreMinPct: 30.0,
    frenteMinimoM: 15.0,
    loteMinimoM2: 800.0,
    estacionamientosRequeridos: "1 cada 35m²",
    ordenanzaReferencia: "Ord. 410-MDLM",
    fechaAprobacion: "2023-07-22",
    vigencia: true,
    notasNormativas:
      "Comercio financiero, gastronomía gourmet, centros corporativos y automotrices.",
    updatedAt: "2026-06-28T16:45:00Z",
    updatedBy: "Diego Palacios",
  },
];
